[biomes]
enabled = false
textFadeInTime = 10
textDisplayTime = 50
textFadeOutTime = 10
textCooldownTime = 80
textColor = "ffffff"
textSize = 2.1
renderShadow = true
textYOffset = -33
textXOffset = 0
biomeBlacklist = "[minecraft:the_end, minecraft:river, minecraft:frozen_river]"
recentBiomeCacheSize = 3
centerText = true
resetBiomeCacheOnDimensionChange = true
onlyUpdateAtSurface = true
[dimensions]
enabled = true
textFadeInTime = 10
textDisplayTime = 20
textFadeOutTime = 10
textColor = "ffffff"
textSize = 2.0
renderShadow = true
textYOffset = -32
textXOffset = 0
dimensionBlacklist = "[]"
centerText = true
onlyUpdateAtSurface = false
[sound]
biomeVolume = 1.0
biomePitch = 1.0
dimensionVolume = 1.0
dimensionPitch = 1.0
